### ISSUE TITLE
Support Grakn's debug mode in Windows

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-common#37]
## Problem to Solve

The Windows batch script has not been updated to support Grakn's debug mode yet.

## Current Workaround

Don't debug in Windows.

## Proposed Solution

Update the script.

## Additional Information

The shell script supports the --debug flag.

**Comment by lolski** [comment]
[Triaged] I am placing it under 2.0 production with priority "medium", since the user can live without being able to run Windows Grakn Core without debug mode, at least for now.

**Comment by haikalpribadi** [comment]
I think this can be post-production

**Comment by flyingsilverfin** [comment]
--debug does switch the classpath on windows to include RocksDB's development binary, and has done so as early as July 2021 (~TypeDB 2.3.0)
